config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'recipes#index'
  resources :users, only: [:new, :create, :edit, :update]
  resources :recipes do
    resources :questions
    collection do
      get 'search'
    end
  end
  post '/recipes/guest_sign_in', to: 'recipes#new_guest'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '基本の家庭料理' },
    { id: 3, name: 'おもてなし料理' },
    { id: 4, name: 'スイーツ・お菓子' }
  ]
end

app/models/question.rb
class Question < ApplicationRecord
  # 空の投稿を保存できないようにする
  with_options presence: true do
    validates :text, length: { in: 1..1000 }
  end

  has_many :users
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :genre

  # 検索の処理
  def self.search(search)
    if search != ""
      Recipe.where('dish_name LIKE(?)', "%#{search}%")
    else
      Recipe.all
    end
  end

  # 空の投稿を保存できないようにする
  with_options presence: true do
    validates :dish_name
    validates :image
    validates :ingredient
    validates :detail
  end

  # ジャンルの選択が「--」の時は保存できないようにする
  validates :genre_id, numericality: { other_than: 1 }

  belongs_to :user
  has_many :questions
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  with_options presence: true, length: { minimum: 6 } do
    VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
    validates :password, format: { with: VALID_PASSWORD_REGEX }
    validates :password_confirmation, format: { with: VALID_PASSWORD_REGEX }
  end

  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  has_many :questions
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def new_guest
    user = User.find_or_create_by!(email: 'guest@email.com') do |user|
      user.password = 'guest1111'
      user.password_confirmation = 'guest1111'
      user.nickname = 'ゲスト'
    end
    sign_in user
    redirect_to root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :teacher])
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @questions = Question.where(recipe_id: params[:recipe_id])
    @question = Question.new
  end

  def create
    @question = Question.new(text: params[:question][:text], recipe_id: params[:recipe_id], user_id: current_user.id)
    ActionCable.server.broadcast 'question_channel', content: @question if @question.save
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:edit, :show, :update, :destroy]
  before_action :move_to_new, only: [:new]

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    @recipes = Recipe.all.order(created_at: :desc)
  end

  def destroy
    if @recipe.destroy
      redirect_to root_path
    else
      render :edit
    end
  end

  def edit
  end

  def show
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end

  def search
    @recipes = Recipe.search(params[:keyword])
  end

  private

  def recipe_params
    params.require(:recipe).permit(:dish_name, :genre_id, :ingredient, :detail, :image).merge(user_id: current_user.id)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def move_to_new
    redirect_to '/users/sign_in' unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>教えて！料理先生</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/questions/new.html.erb
<div class="questions-contents">
  <link href="/questions/new.css" rel="stylesheet">

  <header class="recipes-create-header">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color:#2e499d;">
      <%= link_to image_tag('/assets/logo-y.png' , size: '260x28'), "/" %>
    </nav>
  </header>

  <div class="questions-main">
    <h2 class="questions-title">質問を作成する</h2>
    <%= form_with model:@question, url:recipe_questions_path, id: 'new_question', local: true do |f| %>
      <div class="row">
        <div class="col-8">
          <%= f.text_area :text, class:"questions-text", id:"question_text", placeholder:"質問内容（必須 1,000文字まで）", size: "48x4", maxlength:"1000" %>
        </div>
        <div class="col-4">
          <%= f.submit "送信", id: "submit", class:"question-post-btn" %>
          <%= link_to 'もどる', root_path, class:"question-back-btn" %>
        </div>
      </div>
    <% end %>

    <div class="questions">
        <div class="question-user-name">
          <!-- 投稿したユーザー名情報を出力する -->
          <% @questions.reverse_each do |question| %>
            <p>投稿者: <%= current_user.nickname %></p>
          <% end %>
        </div>
      <div class="question-date">
        <!-- 投稿した時刻を出力する -->
        <% @questions.reverse_each do |question| %>
        <p>投稿日時: <%= question.created_at %></p>
        <% end %>
      </div>
      <div class="question-message">
        <% @questions.reverse_each do |question| %>
          <p><%= question.text %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="recipes-create-contents">

  <header class="recipes-create-header">
    <%= link_to image_tag('/assets/logo-y.png' , size: '270x28'), "/" %>
  </header>

  <div class="recipes-create-main">
    <h2 class="recipes-create-title">レシピを編集する</h2>

    <%= form_with model: @recipe, id: 'new_recipe', local: true do |f| %>
      
      <%# 料理画像 %>
      <div class="img-upload">
        <div class="weight-bold-text">
          料理画像
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id:"recipe-image" %>
        </div>
      </div>
      <%# /料理画像 %>

      <%# 料理名と材料、作り方 %>
      <div class="new-recipes">

        <div class="weight-bold-text">レシピ名
          <span class="indispensable">必須</span>
        </div>

        <%= f.text_area :dish_name, class:"recipes-text", id:"recipe-name", placeholder:"レシピ名（必須 40文字まで)", maxlength:"40" %>

        <%# ジャンル %>
        <div class="recipes-genre">
          <div class="weight-bold-text">
            ジャンル
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"recipe-genre"}) %>
        </div>
        <%# /ジャンル %>

        <div class="recipes-explain">

          <div class="weight-bold-text">材料
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :ingredient, class:"ingredients-text", id:"ingredient", placeholder:"材料（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>

          <div class="weight-bold-text">作り方
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :detail, class:"recipe-detail", id:"recipe-details", placeholder:"作り方（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>

        </div>

      </div>
      <%# /料理名と材料、作り方 %>

      <%# 下部ボタン %>
      <div class="post-btn-contents">
        <%= f.submit "変更する", class:"post-btn" %>
        <%= link_to 'もどる', recipe_path(@recipe.id), class:"back-btn" %>
      </div>
      <%# /下部ボタン %>

    <% end %>
  </div>


</div>

app/views/recipes/index.html.erb
<div class="all">
  <%= render "shared/header" %>

  <link href="index.css" rel="stylesheet">

  <div class='main'>

    <%# 画面上部の「料理講師に質問できるレシピアプリ」帯部分 %>
    <div class="jumbotron jumbotron-fluid">
      <div class="container jumbotron-container">
        <h1 class="site-name">料理講師に質問できるレシピアプリ</h1>
        <p class="lead">“教えて！料理先生”はレシピだけではわからないことを</p>
        <p class="lead">レシピ考案者である料理講師に質問できるレシピアプリです</p>
      </div>
    </div>
    <%# /画面上部の「料理講師に質問できるレシピアプリ」帯部分 %>

    <%# コンテンツエリア %>
    <main class="container-fluid contents">

      <div class="content-primary">

        <div class='title'>
          <%# <img src="/assets/logo_dish-r.png" width="35px" height="18px" alt="ロゴ" class="img-responsive"> %>
          <img src="/assets/logo_dish-r.png" alt="ロゴ" class="img-responsive">
            <h2>新着レシピ</h2>
          <img src="/assets/logo_dish-r.png" alt="ロゴ" class="img-responsive">
        </div>

          <%# 新着レシピ一覧 %>
        <div class='recipe-list'>

          <ul class='recipe-lists'>

            <% if @recipes.present? %>

              <% @recipes.each do |recipe| %>
                  
                <li class='list'>
                  <%= link_to recipe_path(recipe.id) do %>
                    <div class='recipe-img-content'>
                      <%= image_tag recipe.image.variant(resize_to_fill: [280, 200]) %>
                    </div>

                    <h3 class='recipe-name'>
                      <%= recipe.dish_name %>
                    </h3>
                    <h4 class='recipe-genre'>
                      【ジャンル】<%= recipe.genre.name %>
                    </h4>
                  <% end %>
                </li>
                  
              <% end %>

            <% else %>

              <%# レシピがない場合のダミー %>
              <li class='list'>
                <%= link_to "#" do %>
                  <%= image_tag "cooking_shippai", size: '200x200', class: "recipe-img" %>
                  <h3 class='recipe-name'>
                    料理先生！レシピ作ってください
                  </h3>
                <% end %>
              </li>
              <%# //レシピがない場合のダミー %>

            <% end %>

          </ul>

        </div>
        <%# //新着レシピ一覧 %>

      </div>

      <hr class="contents-divider">

      <%# 専属講師による動画教室 %>
      <div class="content-movie">
        <div class='title'>
          <img src="/assets/logo_dish-r.png" alt="ロゴ" class="img-responsive">
            <h2>”教えて！料理先生”専属講師が動画で教える料理の基礎</h2>
          <img src="/assets/logo_dish-r.png" alt="ロゴ" class="img-responsive">
        </div>

        <div class="warning">
          <p>動画を再生するには、videoタグをサポートしたブラウザが必要です。</p>
        </div>

        <div class="movies">
          <video controls poster="assets/samnail.jpg" width="320" height="240">
            <source src="assets/hocho_320.mp4">
          </video>
          <img src="/assets/samnail2.jpg" width="320" height="210" alt="正しい計量動画" class="coming-soon">
        </div>
      </div>
      <%# //専属講師による動画教室 %>

      <hr class="contents-divider">

      <%# 目的別に3ジャンルの部分 %>
      <div class="content-secondary">

        <div class='title'>
          <img src="/assets/logo_dish-r.png" alt="ロゴ" class="img-responsive">
          <h2 class='title'>“教えて！料理先生”は目的別に3ジャンル</h2>
          <img src="/assets/logo_dish-r.png" alt="ロゴ" class="img-responsive">
        </div>

        <div class='genre-list'>

          <div class='genre-body'>

            <div class="genre-image">
              <a href="/"><img src="/assets/nikujaga.jpg" width="180px" height="180px" alt="基本の家庭料理" class="rounded-circle"></a>
            </div>

            <div class="genre-detail">
              <h3>基本の家庭料理</h3>
              <p>おなじみの家庭料理が揃っています。「レシピ通りに作っているけど、なんかちょっと違う」等、料理講師に質問してみましょう！</p>
              <%= link_to 'レシピを見る', root_path, class:"genre-btn" %>
            </div>

          </div>

          <div class='genre-body'>

            <div class="genre-image">
              <a href="/"><img src="/assets/osechi.jpg" width="180px" height="180px" alt="おもてなし料理" class="rounded-circle"></a>
            </div>

            <div class="genre-detail">
              <h3>おもてなし料理</h3>
              <p>流行を取り入れた、おもてなしにぴったりな料理をご紹介。時短テクや、新しい調理方法等、料理講師に聞いてみましょう！</p>
              <%= link_to 'レシピを見る', root_path, class:"genre-btn" %>
            </div>

          </div>

          <div class='genre-body'>

            <div class="genre-image">
              <a href="/"><img src="/assets/appletalt.jpg" width="180px" height="180px" alt="スイーツ・お菓子" class="rounded-circle"></a>
            </div>

            <div class="genre-detail">
              <h3>スイーツ・お菓子</h3>
              <p>記念日用の華やかなケーキから普段使いしたいおやつまで、幅広いレシピが揃っています。製菓講師に細かい部分のコツ等きいてみましょう！</p>
              <%= link_to 'レシピを見る', root_path, class:"genre-btn" %>
            </div>

          </div>

        </div>

      </div>
      <%# /目的別に3ジャンルの部分 %>

    </main>
    <%# /コンテンツエリア %>

    <%= render "shared/footer" %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="recipes-create-contents">

  <header class="recipes-create-header">
    <%= link_to image_tag('/assets/logo-y.png' , size: '270x28'), "/" %>
  </header>

  <div class="recipes-create-main">
    <h2 class="recipes-create-title">レシピを作成する</h2>

    <%= form_with model: @recipe, url: recipes_path, id: 'new_recipe', local: true do |f| %>
      
      <%# 料理画像 %>
      <div class="img-upload">
        <div class="weight-bold-text">
          料理画像
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id:"recipe-image" %>
        </div>
        <%= image_tag @recipe.image.variant(resize_to_fill: [300, 200]), class: 'recipe-image' if @recipe.image.attached? %>
      </div>
      <%# /料理画像 %>

      <%# 料理名と材料、作り方 %>
      <div class="new-recipes">

        <div class="weight-bold-text">レシピ名
          <span class="indispensable">必須</span>
        </div>

        <%= f.text_area :dish_name, class:"recipes-text", id:"recipe-name", placeholder:"レシピ名（必須 40文字まで)", maxlength:"40" %>

        <%# ジャンル %>
        <div class="recipes-genre">
          <div class="weight-bold-text">
            ジャンル
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"recipe-genre"}) %>
        </div>
        <%# /ジャンル %>

        <div class="recipes-explain">

          <div class="weight-bold-text">材料
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :ingredient, class:"ingredients-text", id:"ingredient", placeholder:"材料（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>

          <div class="weight-bold-text">作り方
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :detail, class:"recipe-detail", id:"recipe-details", placeholder:"作り方（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>

        </div>

      </div>
      <%# /料理名と材料、作り方 %>

      <%# 下部ボタン %>
      <div class="post-btn-contents">
        <%= f.submit "投稿する", class:"post-btn" %>
        <%= link_to 'もどる', root_path, class:"back-btn" %>
      </div>
      <%# /下部ボタン %>

    <% end %>
  </div>


</div>

app/views/recipes/search.html.erb
<%= render "shared/header" %>

<div class="contents row">
  <ul><% @recipes.each do |recipe| %>
    <li class='list'>
      <%= link_to recipe_path(recipe.id) do %>
        <div class='recipe-img-content'>
          <%= image_tag recipe.image.variant(resize_to_fill: [280, 200]) %>
        </div>
        <h3 class='recipe-name'>
          <%= recipe.dish_name %>
        </h3>
        <h4 class='recipe-genre'>
          【ジャンル】<%= recipe.genre.name %>
        </h4>
      <% end %>
    </li>
  </ul>  
</div>

<%= render "shared/footer" %>

app/views/recipes/show.html.erb
<%= render "shared/header" %>

<div class="recipe-show">

  <div class="recipe-box">

    <h2 class="name">
      <%= @recipe.dish_name %>
    </h2>

    <h3 class="recipe-creator">レシピ考案　<%= @recipe.user.nickname %>先生</h3>

  </div>

  <%# ーーーーーーーーーレシピ詳細ーーーーーーーーー %>

  <div class='recipe-details'>

    <div class='recipe-img-content-show'>
      <%= image_tag @recipe.image.variant(resize_to_fill: [400, 300]) ,class:"recipe-box-img" %>
    </div>

    <table class="detail-table">
        <tr>
          <th class="detail-recipe">レシピカテゴリー</th>
          <td class="detail-value"><%= @recipe.genre.name %></td>
        </tr>
        <tr>
          <th class="detail-recipe">材料</th>
          <td class="detail-value"><%= @recipe.ingredient %></td>
        </tr>
        <tr>
          <th class="detail-recipe">作り方</th>
          <td class="detail-value"><%= @recipe.detail %></td>
        </tr>
    </table>

  </div>
  <%# ーーーーーーーーーレシピ詳細ーーーーーーーーー %>

  <%# ーーーーーーーーー下部ボタンーーーーーーーーー %>
  <div class="question-btn">

    <%# ログインしているユーザとレシピ投稿しているユーザが同一人物である時、レシピの編集と削除を表示%>
    <% if user_signed_in? && current_user.id == @recipe.user_id %>

      <%= link_to '質問の返答をする', new_recipe_question_path(@recipe.id), class:"comment-btn" %>
      <%= link_to 'レシピの編集', edit_recipe_path(@recipe.id), class: "recipe-red-btn" %>
      <%= link_to '削除', recipe_path, method: :delete, class:'recipe-destroy' %>

    <% else %>
      <% if user_signed_in? %>
        <%= link_to new_recipe_question_path(@recipe.id), class:"comment-btn" do%>
          <%= @recipe.user.nickname %>先生へ質問する
        <% end %>
      <% else %>
        <%= link_to new_recipe_question_path(@recipe.id), class:"comment-btn" do%>
          <%= @recipe.user.nickname %>先生へ質問する
        <% end %>
      <% end %>
    <% end %>

  </div>
  <%# ーーーーーーーーー下部ボタンーーーーーーーーー %>
  
</div>

<%= render "shared/footer" %>

app/views/shared/_footer.html.erb
<hr class="contents-divider">

<footer class="container">
  <p class="float-right"><a href="#">トップに戻る</a></p>
  <p>&copy; 2017-2020 Company, Inc. &middot; <a href="#">プライバシー</a> &middot; <a href="#">利用規約</a></p>
</footer>

app/views/shared/_header.html.erb
<link href="header.css" rel="stylesheet">

<header class='top-page-header'>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color:#2e499d;">

    <div class="container-fluid">

      <a class="navbar-brand" href="/">
        <img src="/assets/logo-y.png" width="260" height="28" alt="教えて！料理先生">
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">

        <ul class="navbar-nav mr-auto mb-2 mb-md-0">

          <% if user_signed_in? %>
            <div class="user_nav grid-6">
              <span><%= link_to current_user.nickname, "/", class: "user-nickname" %></span>
              <span><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></span>
            </div>
          <% else %>
            <div class="grid-6">
              <span><%= link_to 'ログイン', user_session_path, method: :create, class: "login" %></span>
              <span><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></span>
            </div>
          <% end %>

          <div class="grid-6">
            <span><%= link_to '　ゲストログイン（一般ユーザー）', recipes_guest_sign_in_path, method: :post, class: "guest-login" %></span>
          </div>

        </ul>

        <form class="d-flex">
          <%= form_with url: search_recipes_path, local: true, method: :get do |form| %>
            <%= form.text_field :keyword, placeholder: "（現在開発中）レシピ名で検索", class: "search-input" %>
            <%= form.submit "検索", class: "search-btn" %>
          <% end %>
        </form>

          <% if user_signed_in? %>
            <% if current_user.teacher %>
              <%= link_to 'レシピを書く', new_recipe_path, class:"create-recipe-btn" %>
            <% end %>
          <% end %>
      </div>
    </div>
  </nav>

</header>

app/views/shared/_second-header.html.erb
<header class="second-header">
  <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color:#2e499d;">
    <%= link_to image_tag('/assets/logo-y.png' , size: '270x28'), "/" %>
  </nav>
</header>